services:
  web:
    build:
      context: .
    container_name: flask-business-card
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    command: python run.py
