name: Тестирование Flask-проекта

# Когда запускать CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Определение задания
jobs:
  test:
    runs-on: ubuntu-latest  # GitHub будет использовать Linux для запуска

    steps:
      - name: 🔁 Клонировать репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Укажи версию, как у тебя локально

      - name: 🧪 Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Запустить pytest
        run: |
          pytest
